import { PrismaClient, Role, MandiApprovalStatus } from '@prisma/client';

const prisma = new PrismaClient();

// Official 51 Commodities specified in requirements
export const OFFICIAL_COMMODITIES = [
  { name: 'Wheat', category: 'Cereals' },
  { name: 'Paddy', category: 'Cereals' },
  { name: 'Maize', category: 'Cereals' },
  { name: 'Soybean', category: 'Oilseeds' },
  { name: 'Cotton', category: 'Cash Crops' },
  { name: 'Mustard', category: 'Oilseeds' },
  { name: 'Groundnut', category: 'Oilseeds' },
  { name: 'Chana', category: 'Pulses' },
  { name: 'Tur', category: 'Pulses' },
  { name: 'Moong', category: 'Pulses' },
  { name: 'Urad', category: 'Pulses' },
  { name: 'Masoor', category: 'Pulses' },
  { name: 'Bajra', category: 'Cereals' },
  { name: 'Jowar', category: 'Cereals' },
  { name: 'Sugarcane', category: 'Cash Crops' },
  { name: 'Onion', category: 'Vegetables' },
  { name: 'Potato', category: 'Vegetables' },
  { name: 'Tomato', category: 'Vegetables' },
  { name: 'Turmeric', category: 'Spices' },
  { name: 'Coriander', category: 'Spices' },
  { name: 'Cumin', category: 'Spices' },
  { name: 'Garlic', category: 'Spices' },
  { name: 'Ginger', category: 'Spices' },
  { name: 'Peas', category: 'Vegetables' },
  { name: 'Cabbage', category: 'Vegetables' },
  { name: 'Cauliflower', category: 'Vegetables' },
  { name: 'Brinjal', category: 'Vegetables' },
  { name: 'Okra', category: 'Vegetables' },
  { name: 'Green Chilli', category: 'Vegetables' },
  { name: 'Capsicum', category: 'Vegetables' },
  { name: 'Carrot', category: 'Vegetables' },
  { name: 'Radish', category: 'Vegetables' },
  { name: 'Mango', category: 'Fruits' },
  { name: 'Apple', category: 'Fruits' },
  { name: 'Banana', category: 'Fruits' },
  { name: 'Grapes', category: 'Fruits' },
  { name: 'Pomegranate', category: 'Fruits' },
  { name: 'Orange', category: 'Fruits' },
  { name: 'Guava', category: 'Fruits' },
  { name: 'Papaya', category: 'Fruits' },
  { name: 'Watermelon', category: 'Fruits' },
  { name: 'Jute', category: 'Cash Crops' },
  { name: 'Tobacco', category: 'Cash Crops' },
  { name: 'Coconut', category: 'Plantation' },
  { name: 'Areca Nut', category: 'Plantation' },
  { name: 'Sesame', category: 'Oilseeds' },
  { name: 'Sunflower', category: 'Oilseeds' },
  { name: 'Castor', category: 'Oilseeds' },
  { name: 'Barley', category: 'Cereals' },
  { name: 'Ragi', category: 'Cereals' },
  { name: 'Chickpea', category: 'Pulses' },
];

const PIMPRI_PUNE_MANDIS = [
  {
    apmcCode: 'MH-PCMC-001',
    name: 'Morwadi APMC Sub-Yard (Near DY Patil Pimpri)',
    address: 'Sant Tukaram Nagar, Near DY Patil College, Morwadi, Pimpri, Pune 411018',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.6272,
    longitude: 73.8131,
    topCrop: 'Onion, Tomato',
    acceptedCrops: ['Onion', 'Tomato', 'Green Chilli', 'Wheat', 'Soybean'],
    modalPrice: '₹2,750 / qtl',
    priceTrend: '+₹140 today',
    trendDirection: 'up',
    estimatedQueueTime: '15 mins wait',
    activeFarmersCount: 145,
    operatingHours: '05:30 AM - 07:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-002',
    name: 'Pimpri Central Grain & Vegetable Mandi',
    address: 'Station Road, Pimpri Gaon, Pimpri Chinchwad 411017',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.6255,
    longitude: 73.8015,
    topCrop: 'Wheat, Soybean',
    acceptedCrops: ['Wheat', 'Soybean', 'Maize', 'Chana', 'Tur'],
    modalPrice: '₹2,890 / qtl',
    priceTrend: '+₹80 today',
    trendDirection: 'up',
    estimatedQueueTime: '25 mins wait',
    activeFarmersCount: 190,
    operatingHours: '05:00 AM - 08:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-003',
    name: 'Chinchwad Station Krishi Bazaar',
    address: 'Old Pune-Mumbai Highway, Near Railway Station, Chinchwad 411019',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.6348,
    longitude: 73.7887,
    topCrop: 'Peas, Potato',
    acceptedCrops: ['Peas', 'Potato', 'Carrot', 'Cabbage', 'Cauliflower'],
    modalPrice: '₹3,200 / qtl',
    priceTrend: '-₹50 today',
    trendDirection: 'down',
    estimatedQueueTime: '20 mins wait',
    activeFarmersCount: 120,
    operatingHours: '06:00 AM - 06:30 PM',
  },
  {
    apmcCode: 'MH-PCMC-004',
    name: 'Akurdi Railway APMC Yard',
    address: 'Pradhikaran, Sector 26, Akurdi, PCMC 411044',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.6482,
    longitude: 73.7699,
    topCrop: 'Maize, Bajra',
    acceptedCrops: ['Maize', 'Bajra', 'Jowar', 'Ragi', 'Barley'],
    modalPrice: '₹2,420 / qtl',
    priceTrend: '+₹60 today',
    trendDirection: 'up',
    estimatedQueueTime: '15 mins wait',
    activeFarmersCount: 85,
    operatingHours: '06:00 AM - 07:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-005',
    name: 'Nigdi Pradhikaran Farmers Hub',
    address: 'Bhakti Shakti Chowk Road, Nigdi, Pimpri Chinchwad 411044',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.6568,
    longitude: 73.7712,
    topCrop: 'Tomato, Cauliflower',
    acceptedCrops: ['Tomato', 'Cauliflower', 'Cabbage', 'Capsicum', 'Brinjal'],
    modalPrice: '₹2,150 / qtl',
    priceTrend: '+₹110 today',
    trendDirection: 'up',
    estimatedQueueTime: '30 mins wait',
    activeFarmersCount: 110,
    operatingHours: '05:30 AM - 06:30 PM',
  },
  {
    apmcCode: 'MH-PCMC-006',
    name: 'Bhosari MIDC Kisan Yard',
    address: 'Pune-Nashik Highway, Sector 7, Bhosari 411026',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.6186,
    longitude: 73.8446,
    topCrop: 'Onion, Garlic',
    acceptedCrops: ['Onion', 'Garlic', 'Ginger', 'Turmeric', 'Coriander'],
    modalPrice: '₹3,450 / qtl',
    priceTrend: '+₹210 today',
    trendDirection: 'up',
    estimatedQueueTime: '35 mins wait',
    activeFarmersCount: 175,
    operatingHours: '05:00 AM - 08:30 PM',
  },
  {
    apmcCode: 'MH-PCMC-007',
    name: 'Moshi Mega APMC Complex',
    address: 'Moshi-Alandi BRTS Corridor, Moshi, PCMC 412105',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.675,
    longitude: 73.848,
    topCrop: 'Soybean, Groundnut',
    acceptedCrops: ['Soybean', 'Groundnut', 'Sunflower', 'Mustard', 'Cotton', 'Wheat'],
    modalPrice: '₹4,950 / qtl',
    priceTrend: '+₹175 today',
    trendDirection: 'up',
    estimatedQueueTime: '40 mins wait',
    activeFarmersCount: 310,
    operatingHours: '04:30 AM - 09:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-008',
    name: 'Chakan Onion & Vegetable Hub',
    address: 'Market Yard, Shikrapur Road, Chakan 410501',
    district: 'Pune Rural / PCMC',
    state: 'Maharashtra',
    latitude: 18.7562,
    longitude: 73.8569,
    topCrop: 'Onion, Ginger',
    acceptedCrops: ['Onion', 'Ginger', 'Garlic', 'Potato', 'Turmeric'],
    modalPrice: '₹3,100 / qtl',
    priceTrend: '+₹250 today',
    trendDirection: 'up',
    estimatedQueueTime: '45 mins wait',
    activeFarmersCount: 260,
    operatingHours: '04:00 AM - 08:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-009',
    name: 'Talegaon Dabhade Agro Market',
    address: 'Station Road, Talegaon Dabhade, Pune 410506',
    district: 'Pune Rural / PCMC',
    state: 'Maharashtra',
    latitude: 18.7342,
    longitude: 73.6811,
    topCrop: 'Capsicum, Tomato',
    acceptedCrops: ['Capsicum', 'Tomato', 'Cabbage', 'Peas', 'Green Chilli'],
    modalPrice: '₹6,200 / qtl',
    priceTrend: '+₹300 today',
    trendDirection: 'up',
    estimatedQueueTime: '20 mins wait',
    activeFarmersCount: 95,
    operatingHours: '06:00 AM - 05:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-010',
    name: 'Dehu Road APMC Sub-Market',
    address: 'Old Highway Near Cantonment, Dehu Road 412101',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.7189,
    longitude: 73.7225,
    topCrop: 'Paddy, Jowar',
    acceptedCrops: ['Paddy', 'Jowar', 'Bajra', 'Wheat', 'Ragi'],
    modalPrice: '₹3,350 / qtl',
    priceTrend: '+₹40 today',
    trendDirection: 'up',
    estimatedQueueTime: '15 mins wait',
    activeFarmersCount: 70,
    operatingHours: '06:30 AM - 06:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-011',
    name: 'Sangvi Riverbank Vegetable Yard',
    address: 'Old Sangvi Main Road, Near Mula River, PCMC 411027',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.5786,
    longitude: 73.8152,
    topCrop: 'Coriander, Radish',
    acceptedCrops: ['Coriander', 'Radish', 'Carrot', 'Okra', 'Brinjal'],
    modalPrice: '₹1,850 / qtl',
    priceTrend: '-₹20 today',
    trendDirection: 'down',
    estimatedQueueTime: '10 mins wait',
    activeFarmersCount: 65,
    operatingHours: '05:30 AM - 06:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-012',
    name: 'Pimple Saudagar Direct Farmer Market',
    address: 'Kunad Chowk, Pimple Saudagar, PCMC 411027',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.5987,
    longitude: 73.7885,
    topCrop: 'Papaya, Guava',
    acceptedCrops: ['Papaya', 'Guava', 'Banana', 'Mango', 'Pomegranate', 'Tomato'],
    modalPrice: '₹4,100 / qtl',
    priceTrend: '+₹150 today',
    trendDirection: 'up',
    estimatedQueueTime: '15 mins wait',
    activeFarmersCount: 88,
    operatingHours: '06:00 AM - 07:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-013',
    name: 'Wakad Kisan Agro Center',
    address: 'Datta Mandir Road, Wakad, PCMC 411057',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.5982,
    longitude: 73.7621,
    topCrop: 'Pomegranate, Grapes',
    acceptedCrops: ['Pomegranate', 'Grapes', 'Orange', 'Banana', 'Papaya'],
    modalPrice: '₹5,800 / qtl',
    priceTrend: '+₹320 today',
    trendDirection: 'up',
    estimatedQueueTime: '20 mins wait',
    activeFarmersCount: 105,
    operatingHours: '06:00 AM - 07:30 PM',
  },
  {
    apmcCode: 'MH-PCMC-014',
    name: 'Hinjawadi Agri Produce Yard',
    address: 'Phase 1 Chowk, Hinjawadi, Pune 411057',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.5912,
    longitude: 73.7389,
    topCrop: 'Cabbage, Capsicum',
    acceptedCrops: ['Cabbage', 'Capsicum', 'Cauliflower', 'Tomato', 'Green Chilli'],
    modalPrice: '₹2,650 / qtl',
    priceTrend: '+₹90 today',
    trendDirection: 'up',
    estimatedQueueTime: '20 mins wait',
    activeFarmersCount: 92,
    operatingHours: '06:00 AM - 07:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-015',
    name: 'Ravet Farmers Daily Bazaar',
    address: 'Sector 29, Near Expressway Toll Plaza, Ravet 412101',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.6455,
    longitude: 73.7441,
    topCrop: 'Wheat, Mustard',
    acceptedCrops: ['Wheat', 'Mustard', 'Chana', 'Groundnut', 'Moong'],
    modalPrice: '₹2,950 / qtl',
    priceTrend: '+₹75 today',
    trendDirection: 'up',
    estimatedQueueTime: '15 mins wait',
    activeFarmersCount: 78,
    operatingHours: '06:00 AM - 06:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-016',
    name: 'Thergaon Mandi Yard',
    address: 'Dange Chowk Road, Thergaon, PCMC 411033',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.6124,
    longitude: 73.7745,
    topCrop: 'Brinjal, Okra',
    acceptedCrops: ['Brinjal', 'Okra', 'Tomato', 'Cabbage', 'Green Chilli'],
    modalPrice: '₹2,400 / qtl',
    priceTrend: '+₹40 today',
    trendDirection: 'up',
    estimatedQueueTime: '20 mins wait',
    activeFarmersCount: 82,
    operatingHours: '05:30 AM - 06:30 PM',
  },
  {
    apmcCode: 'MH-PCMC-017',
    name: 'Rahatani Krishi Sub-Center',
    address: 'Saudagar-Rahatani Link Road, Rahatani 411017',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.6015,
    longitude: 73.7842,
    topCrop: 'Green Chilli, Okra',
    acceptedCrops: ['Green Chilli', 'Okra', 'Brinjal', 'Tomato', 'Coriander'],
    modalPrice: '₹1,950 / qtl',
    priceTrend: '-₹30 today',
    trendDirection: 'down',
    estimatedQueueTime: '15 mins wait',
    activeFarmersCount: 60,
    operatingHours: '06:00 AM - 06:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-018',
    name: 'Kalewadi Main Produce Yard',
    address: 'Kalewadi Phata, Pimpri Chinchwad 411017',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.6152,
    longitude: 73.7998,
    topCrop: 'Onion, Potato',
    acceptedCrops: ['Onion', 'Potato', 'Garlic', 'Ginger', 'Tomato'],
    modalPrice: '₹2,720 / qtl',
    priceTrend: '+₹110 today',
    trendDirection: 'up',
    estimatedQueueTime: '25 mins wait',
    activeFarmersCount: 115,
    operatingHours: '05:30 AM - 07:00 PM',
  },
  {
    apmcCode: 'MH-PCMC-019',
    name: 'Kasarwadi Grain Hub',
    address: 'Bombay-Pune Highway, Kasarwadi, PCMC 411034',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.5988,
    longitude: 73.8214,
    topCrop: 'Tur, Moong',
    acceptedCrops: ['Tur', 'Moong', 'Urad', 'Chana', 'Masoor', 'Chickpea', 'Jowar'],
    modalPrice: '₹7,450 / qtl',
    priceTrend: '+₹180 today',
    trendDirection: 'up',
    estimatedQueueTime: '25 mins wait',
    activeFarmersCount: 140,
    operatingHours: '06:00 AM - 07:30 PM',
  },
  {
    apmcCode: 'MH-PCMC-020',
    name: 'Dapodi APMC Yard',
    address: 'Near Dapodi Station, Dapodi, PCMC 411012',
    district: 'Pimpri Chinchwad, Pune',
    state: 'Maharashtra',
    latitude: 18.5833,
    longitude: 73.8333,
    topCrop: 'Banana, Papaya',
    acceptedCrops: ['Banana', 'Papaya', 'Watermelon', 'Guava', 'Orange'],
    modalPrice: '₹2,200 / qtl',
    priceTrend: '+₹50 today',
    trendDirection: 'up',
    estimatedQueueTime: '15 mins wait',
    activeFarmersCount: 75,
    operatingHours: '05:30 AM - 06:00 PM',
  },
  {
    apmcCode: 'MH-PUNE-021',
    name: 'Pune Gultekdi Market Yard (Main Mega Terminal)',
    address: 'Gultekdi, Swargate, Pune 411037',
    district: 'Pune City',
    state: 'Maharashtra',
    latitude: 18.4975,
    longitude: 73.8683,
    topCrop: 'Onion, Soybean, Cotton, Grapes',
    acceptedCrops: ['Onion', 'Soybean', 'Cotton', 'Grapes', 'Pomegranate', 'Wheat', 'Tomato', 'Paddy'],
    modalPrice: '₹4,920 / qtl',
    priceTrend: '+₹220 today',
    trendDirection: 'up',
    estimatedQueueTime: '45 mins wait',
    activeFarmersCount: 520,
    operatingHours: '04:00 AM - 09:00 PM',
  },
  {
    apmcCode: 'MH-PUNE-022',
    name: 'Khadki Agricultural Bazaar',
    address: 'Old Pune-Mumbai Road, Khadki, Pune 411003',
    district: 'Pune City / PCMC',
    state: 'Maharashtra',
    latitude: 18.5638,
    longitude: 73.8467,
    topCrop: 'Vegetables, Wheat',
    acceptedCrops: ['Wheat', 'Potato', 'Onion', 'Cabbage', 'Cauliflower', 'Carrot'],
    modalPrice: '₹2,820 / qtl',
    priceTrend: '+₹60 today',
    trendDirection: 'up',
    estimatedQueueTime: '20 mins wait',
    activeFarmersCount: 90,
    operatingHours: '06:00 AM - 06:30 PM',
  },
];

async function main() {
  console.log('🌱 Starting database seeding for official commodities & Pune/PCMC mandis...');

  // 1. Seed Official 51 Commodities
  console.log(`📦 Seeding ${OFFICIAL_COMMODITIES.length} official commodities...`);
  for (const item of OFFICIAL_COMMODITIES) {
    await prisma.commodity.upsert({
      where: { name: item.name },
      update: { category: item.category },
      create: {
        name: item.name,
        category: item.category,
        defaultUnit: 'kg',
      },
    });
  }

  // 2. Seed Mandis
  console.log(`🏛️  Seeding ${PIMPRI_PUNE_MANDIS.length} real APMC mandis...`);
  for (const mandi of PIMPRI_PUNE_MANDIS) {
    const operatorEmail = `${mandi.apmcCode.toLowerCase().replace(/-/g, '_')}@farmersetu.in`;

    // 2.1 Upsert Operator User
    const operatorUser = await prisma.user.upsert({
      where: { email: operatorEmail },
      update: {
        name: `${mandi.name.split(' ')[0]} Operator`,
        role: Role.MANDI_OPERATOR,
        isVerified: true,
      },
      create: {
        email: operatorEmail,
        name: `${mandi.name.split(' ')[0]} Operator`,
        passwordHash: '$2b$10$epG/2q1/d51v.1iG.hH2.e1vL3p24r.15iT41235123451234512',
        role: Role.MANDI_OPERATOR,
        isVerified: true,
      },
    });

    // 2.2 Upsert MandiProfile
    const mandiProfile = await prisma.mandiProfile.upsert({
      where: { userId: operatorUser.id },
      update: {
        mandiName: mandi.name,
        apmcCode: mandi.apmcCode,
        address: mandi.address,
        district: mandi.district,
        state: mandi.state,
        latitude: mandi.latitude,
        longitude: mandi.longitude,
        topCrop: mandi.topCrop,
        acceptedCrops: mandi.acceptedCrops,
        modalPrice: mandi.modalPrice,
        priceTrend: mandi.priceTrend,
        trendDirection: mandi.trendDirection,
        estimatedQueueTime: mandi.estimatedQueueTime,
        activeFarmersCount: mandi.activeFarmersCount,
        operatingHours: mandi.operatingHours,
        approvalStatus: MandiApprovalStatus.APPROVED,
        approvedAt: new Date(),
        isOpen: true,
      },
      create: {
        userId: operatorUser.id,
        mandiName: mandi.name,
        apmcCode: mandi.apmcCode,
        address: mandi.address,
        district: mandi.district,
        state: mandi.state,
        latitude: mandi.latitude,
        longitude: mandi.longitude,
        topCrop: mandi.topCrop,
        acceptedCrops: mandi.acceptedCrops,
        modalPrice: mandi.modalPrice,
        priceTrend: mandi.priceTrend,
        trendDirection: mandi.trendDirection,
        estimatedQueueTime: mandi.estimatedQueueTime,
        activeFarmersCount: mandi.activeFarmersCount,
        operatingHours: mandi.operatingHours,
        approvalStatus: MandiApprovalStatus.APPROVED,
        approvedAt: new Date(),
        isOpen: true,
      },
    });

    // 2.3 Upsert Active Mandi Auction Slots for today and upcoming days
    const todayStr = new Date().toISOString().split('T')[0];
    const tomorrowStr = new Date(Date.now() + 86400000).toISOString().split('T')[0];

    const slotData = [
      {
        crop: mandi.acceptedCrops[0] || 'Onion',
        date: todayStr,
        startTime: '07:00',
        endTime: '11:00',
        totalCapacityQuintals: 500,
        maxFarmers: 40,
        availableBookings: 28,
        bookedFarmers: 12,
      },
      {
        crop: mandi.acceptedCrops[1] || mandi.acceptedCrops[0] || 'Tomato',
        date: todayStr,
        startTime: '11:30',
        endTime: '15:30',
        totalCapacityQuintals: 450,
        maxFarmers: 35,
        availableBookings: 25,
        bookedFarmers: 10,
      },
      {
        crop: mandi.acceptedCrops[0] || 'Wheat',
        date: tomorrowStr,
        startTime: '07:00',
        endTime: '11:00',
        totalCapacityQuintals: 600,
        maxFarmers: 50,
        availableBookings: 45,
        bookedFarmers: 5,
      },
    ];

    for (const slot of slotData) {
      const existingSlot = await prisma.mandiSlot.findFirst({
        where: {
          mandiProfileId: mandiProfile.id,
          date: slot.date,
          startTime: slot.startTime,
        },
      });

      if (!existingSlot) {
        await prisma.mandiSlot.create({
          data: {
            mandiProfileId: mandiProfile.id,
            crop: slot.crop,
            date: slot.date,
            startTime: slot.startTime,
            endTime: slot.endTime,
            totalCapacityQuintals: slot.totalCapacityQuintals,
            maxFarmers: slot.maxFarmers,
            availableBookings: slot.availableBookings,
            bookedFarmers: slot.bookedFarmers,
            isActive: true,
          },
        });
      }
    }
  }

  console.log(`✅ Successfully seeded 51 official commodities and ${PIMPRI_PUNE_MANDIS.length} mandis with multi-crop support!`);
}

main()
  .catch((e) => {
    console.error('❌ Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
